#!/bin/bash
# 跨平台打包说明脚本

echo "=========================================="
echo "跨平台打包说明"
echo "=========================================="
echo ""
echo "PyInstaller 不支持跨平台打包："
echo "  - 在 macOS 上只能打包 macOS 应用"
echo "  - 在 Windows 上只能打包 Windows 应用"
echo ""
echo "解决方案："
echo ""
echo "1. 使用 GitHub Actions（推荐）"
echo "   - 将代码推送到 GitHub"
echo "   - 使用 .github/workflows/build.yml 自动打包"
echo "   - 在 Windows 和 macOS 环境中分别打包"
echo ""
echo "2. 使用虚拟机"
echo "   - 在 macOS 上安装 Windows 虚拟机（Parallels/VMware）"
echo "   - 在虚拟机中运行 build_windows.bat"
echo ""
echo "3. 使用 Docker（高级）"
echo "   - 使用 Windows 容器进行打包"
echo ""
echo "4. 找有 Windows 电脑的朋友帮忙"
echo "   - 将代码复制到 Windows 电脑"
echo "   - 运行 build_windows.bat"
echo ""
echo "=========================================="
echo "当前系统：macOS"
echo "可以打包：macOS 应用（使用 ./build_macos.sh）"
echo "无法打包：Windows 应用"
echo "=========================================="

